"""Initial migration.

Revision ID: 2977ec2115da
Revises: 
Create Date: 2024-07-23 21:30:06.033503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2977ec2115da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
